# Configuration file for unit test runner at http://travis-ci.org/#!/drush-ops/drush
language: php
php:
  - 5.3
  - 5.4
env:
  - UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--exclude-group=make
  - UNISH_DB_URL=mysql://root:@127.0.0.1 PHPUNIT_ARGS=--group=make
  - UNISH_DB_URL=pgsql://postgres:@127.0.0.1 PHPUNIT_ARGS=--exclude-group=make
  - UNISH_DB_URL=pgsql://postgres:@127.0.0.1 PHPUNIT_ARGS=--group=make
  - UNISH_DB_URL=sqlite://none/of/this/matters
before_script:
  - export UNISH_DRUSH="${PWD}/drush" && cd tests
script: phpunit $PHPUNIT_ARGS

